;;; init-loader-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from init-loader.el

(autoload 'init-loader-load "init-loader" "\
Load configuration files in INIT-DIR.

(fn &optional (INIT-DIR init-loader-directory))")
(autoload 'init-loader-show-log "init-loader" "\
Show init-loader log buffer." t)
(register-definition-prefixes "init-loader" '("init-loader-"))

;;; End of scraped data

(provide 'init-loader-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; init-loader-autoloads.el ends here
