;;; auto-async-byte-compile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auto-async-byte-compile.el

(register-definition-prefixes "auto-async-byte-compile" '("aabc/" "auto-async-byte-compile" "enable-auto-async-byte-compile-mode"))

;;; End of scraped data

(provide 'auto-async-byte-compile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-async-byte-compile-autoloads.el ends here
