;;; w32-ime-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from w32-ime.el

(autoload 'w32-ime-initialize "w32-ime" "\
Initialize w32-ime.el.")
(register-definition-prefixes "w32-ime" '("w32-ime-"))

;;; End of scraped data

(provide 'w32-ime-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; w32-ime-autoloads.el ends here
