;;; sequential-command-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sequential-command.el

(register-definition-prefixes "sequential-command" '("define-sequential-command" "seq"))


;;; Generated autoloads from sequential-command-config.el

(register-definition-prefixes "sequential-command-config" '("seq"))

;;; End of scraped data

(provide 'sequential-command-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sequential-command-autoloads.el ends here
