;;; egg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from egg.el

(autoload 'egg-minor-mode "egg" "\
Turn-on egg-minor-mode which would enable key bindings for
egg in current buffer.\\<egg-minor-mode-map>
\\[egg-start-new-branch] start a new branch from the current HEAD.
\\[egg-status] shows the repo's current status
\\[egg-commit-log-edit] start editing the commit message for the current staged changes.
\\[egg-file-stage-current-file] stage new changes of the current file
\\[egg-log] shows repo's history
\\[egg-file-checkout-other-version] checkout another version of the current file
\\[egg-file-cancel-modifications] delete unstaged modifications in the current file
\\[egg-next-action] perform the next logical action
\\[egg-file-diff] compare file with index or other commits
\\[egg-file-version-other-window] show other version of the current file.

\\{egg-minor-mode-map}

(fn &optional ARG)" t)
(autoload 'egg-minor-mode-find-file-hook "egg")
(add-hook 'find-file-hook 'egg-git-dir)
(add-hook 'find-file-hook 'egg-minor-mode-find-file-hook)
(register-definition-prefixes "egg" '("commit" "define-egg-buffer" "diff" "egg-" "file-log" "list-nav" "log" "query:commit" "status" "tag:msg" "with-current-"))


;;; Generated autoloads from egg-base.el

(register-definition-prefixes "egg-base" '("dolist-done" "egg-" "invoked-interactively-p" "subseq"))


;;; Generated autoloads from egg-const.el

(register-definition-prefixes "egg-const" '("egg-"))


;;; Generated autoloads from egg-custom.el

(register-definition-prefixes "egg-custom" '("egg-"))


;;; Generated autoloads from egg-diff.el

(register-definition-prefixes "egg-diff" '("egg-"))


;;; Generated autoloads from egg-git.el

(register-definition-prefixes "egg-git" '("egg-" "with-"))


;;; Generated autoloads from egg-grep.el

(autoload 'egg-grep-process-setup "egg-grep" "\
Setup compilation variables and buffer for `egg-grep'.
Set up `compilation-exit-message-function' and run `egg-grep-setup-hook'.")
(autoload 'egg-grep-mode "egg-grep" "\
Sets `compilation-last-buffer' and `compilation-window-height'.

(fn)")
(autoload 'egg-grep "egg-grep" "\


(fn LEVEL)" t)
(register-definition-prefixes "egg-grep" '("egg-grep-"))


;;; Generated autoloads from egg-key.el

(register-definition-prefixes "egg-key" '("egg-" "with-egg-key-buffer"))


;;; Generated autoloads from egg-svn.el

(register-definition-prefixes "egg-svn" '("egg-" "with-egg-temp-direct-mapping"))

;;; End of scraped data

(provide 'egg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; egg-autoloads.el ends here
